modLoader="javafml" #mandatory
loaderVersion="[24,)" #mandatory (24 is current forge version)
credits="Sky" #optional
authors="Sky" #optional

[[mods]] #mandatory
modId="cx" #mandatory
version="0.1.1" #mandatory
displayName="SuperCyber Mod" #mandatory
description='''
This is my mod.
It's great.
'''

[[dependencies.cx]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[25,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.cx]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.3]"
    ordering="NONE"
    side="BOTH"